Repository woodpecker-ci/plugin-git, pull requests merged in 2022-05, with the labels that each got.

#21 Add git-lfs
  docker/Dockerfile.multiarch
Labels: feature

#24 Add an `lfs` setting which lets you disable Git LFS
  main.go
  plugin.go
  plugin_test.go
  types.go
Labels: enhancement

#23 Add basic docs page
  README.md
  docs.md
Labels: documentation
