Repository woodpecker-ci/plugin-git, pull requests merged in 2023-10, with the labels that each got.

#92 Fix renovate labels
  renovate.json
Labels: bug

#91 Use woodpecker plugin instead of drone one
  .woodpecker/test-release.yml
Labels: enhancement

#97 Use correct ref spec
  docs.md
Labels: documentation

#100 move flags into own file
  flags.go
  main.go
Labels: enhancement
